CREATE VIEW Balance_View
AS
SELECT studentbasicinformation.StudentName,
studentbasicinformation.StudentSurname,
studentbasicinformation.StudentRollNo, 
studentbasicinformation.StudentAddress,
studentbasicinformation.StudentGender, 
studentbasicinformation.StudentAge,
studentbasicinformation.StudentCity,
studentadmissionpaymentdetails.AmountBalance
FROM 
studentbasicinformation
INNER JOIN 
studentadmissionpaymentdetails 
ON
studentbasicinformation.StudentRollNo = studentadmissionpaymentdetails.StudentRollNo;
